"""Generic ROS 2 + Gazebo Classic launch file generator.

Generates a temporary ``generated_launch_<timestamp>.py`` in the task directory
by writing a ROS 2 Python launch description that:
- Starts gzserver with the specified world (or empty world)
- Spawns each robot via ``spawn_entity.py`` (SDF) or ``robot_state_publisher`` (URDF)

The generated file is returned as a Path and is suitable for ``ros2 launch <path>``.
"""

from __future__ import annotations

import textwrap
import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cornet.config.schema import RobotConfig


def generate(config: "RobotConfig", task_dir: Path) -> Path:
    """Generate a ROS 2 launch file for the given robot config.

    Args:
        config: The ``robot`` section of a UnifiedConfig.
        task_dir: Directory of the task (generated file is written here).

    Returns:
        Path to the generated ``.py`` launch file.
    """
    world_arg = config.world if config.world else ""
    robot_blocks = []
    needs_xacro = False

    for robot in config.robots:
        pose = robot.pose
        if robot.model.type == "sdf":
            block = textwrap.dedent(
                f"""\
                ExecuteProcess(
                    cmd=[
                        "ros2", "run", "gazebo_ros", "spawn_entity.py",
                        "-entity", "{robot.name}",
                        "-file", "{robot.model.path}",
                        "-x", "{pose.x}", "-y", "{pose.y}", "-z", "{pose.z}",
                        "-R", "{pose.roll}", "-P", "{pose.pitch}", "-Y", "{pose.yaw}",
                    ],
                    output="screen",
                ),
                """
            ).strip()
        else:
            # URDF: use robot_state_publisher
            # Handle xacro extension
            if robot.model.path.endswith(".xacro"):
                urdf_load = f"xacro.process_file('{robot.model.path}').toxml()"
                needs_xacro = True
            else:
                urdf_load = f"open('{robot.model.path}').read()"

            block = textwrap.dedent(
                f"""\
                # {robot.name}: URDF via robot_state_publisher
                Node(
                    package="robot_state_publisher",
                    executable="robot_state_publisher",
                    name="robot_state_publisher_{robot.name}",
                    namespace="{robot.ros_namespace or robot.name}",
                    parameters=[{{"robot_description": {urdf_load}}}],
                    output="screen",
                ),
                """
            ).strip()

        robot_blocks.append(block)

    import_lines = [
        "# Auto-generated by cornet.gazebo.generic_launch — do not edit",
        "from launch import LaunchDescription",
        "from launch.actions import ExecuteProcess",
        "from launch_ros.actions import Node",
    ]
    if needs_xacro:
        import_lines.append("import xacro")

    launch_lines = [
        *import_lines,
        "",
        "def generate_launch_description():",
        "    return LaunchDescription([",
        "        ExecuteProcess(",
        f"            cmd=[\"gzserver\", \"--verbose\", \"{world_arg}\"],",
        "            output=\"screen\",",
        "        ),",
        "        ExecuteProcess(",
        "            cmd=[\"gzclient\"],",
        "            output=\"screen\",",
        "        ),",
    ]

    for block in robot_blocks:
        for line in block.splitlines():
            launch_lines.append(f"        {line}")

    launch_lines.extend([
        "    ])",
        "",
    ])

    launch_code = "\n".join(launch_lines)

    out_path = task_dir / f"generated_launch_{int(time.time())}.py"
    out_path.write_text(launch_code)
    return out_path
